#!/usr/bin/env python
'''
    ./configure type1 type2 ...

Description

    Generate vector.h and vector.c for the input type list. See
    builtins, as well as a test file for each type. the types
    are listed in a yaml config file.

        ./configure conf.yaml

    for an example config see example-conf.yaml

    build test programs

        ./build-tests

    run test program, e.g. for doubles

        ./test-dvector
'''

import sys
import vectypes
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('config',help='config for types')
parser.add_argument('--prefix',default='vector',
                    help='outputs will be {prefix}.h and {prefix}.c')

def main():
    args = parser.parse_args()

    conf=vectypes.read_config(args.config)
    g = vectypes.Generator(conf)
    g.write(prefix=args.prefix)

main()
